version: 2.1
orbs:
  node: circleci/node@5.1
  jira: circleci/jira@2.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
  deploy:
      docker:
        - image: cimg/node:16.14
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: npm
        - run:
            name: Simulate deployment
            command: |
              echo "Deploying application version 1.0.0"
              echo "Deployment to development environment complete! (Simulation)"
        - jira/notify:
            environment: staging
            environment_type: staging
            job_type: deployment
            pipeline_id: << pipeline.id >>
            pipeline_number: << pipeline.number >>

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          post-steps:
            - jira/notify:
                job_type: build
                environment_type: development
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
          context: Jira
      - deploy:
          requires:
            - build-and-test
          post-steps:
            - jira/notify:
                environment_type: development
                environment: development
                pipeline_id: << pipeline.id >>
                pipeline_number: << pipeline.number >>
          context: Jira
          filters:
            branches:
              only: main