version: 2.1
orbs:
  node: circleci/node@5.0.2
  jira: circleci/jira@1.3.1

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - jira/notify:
          job_type: build
          environment_type: development
          
  deploy:
    docker:
      - image: cimg/node:16.14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Simulate deployment
          command: |
            echo "Deploying application version $(node -p \"require('./package.json').version\")"
            echo "Deployment to development environment completed!"
      - jira/notify:
          environment_type: development
          environment: development
          job_type: deployment

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test:
          context: Jira
      - deploy:
          context: Jira
          requires:
            - build-and-test
          filters:
            branches:
              only: main